version: '3'

services:
  angular_frontend:
    image: node:18.15.0
    container_name: test_task_angular_frontend
    hostname: test_task_angular_frontend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '4200:4200'
    command: ["bash", "-c", "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"]
