version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: test_task_db
    hostname: test_task_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_task_symfony4_api
    hostname: test_task_symfony4_api
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}
    ports:
      - '8000:8000'   
    command: >
      bash -c "composer install --no-interaction --optimize-autoloader --prefer-dist --no-scripts
      && php bin/console cache:clear && sleep 30
      && php bin/console doctrine:migrations:migrate
      && symfony server:start"

volumes:
  db_data:
